### ISSUE TITLE
Laadi käännökset palveluun ohjaamisen tietomallin käsitteille

### ISSUE THREAD

**Issue by jokimaki** [omahoito/definitions#33]
Laadi käännökset (ja kuvaukset) https://github.com/omahoito/definitions/blob/master/glossary.md sivulle seuraavista käsitteistä:

![](http://www.plantuml.com/plantuml/svg/ZL9RQWCn3FpNAOm_2mdqI28rHRMpMYfx8PJUfcVe1NAnAdxK-t2X--VPcT7eSGaeOWGnufAIc0ym-adYTuf9PYJliK218tm2NB80XT1Zexyw3kpLWpY_FSR4mXHTaV9Cr-J5hGmiatTQRyQmk93IPAjN1Jpp2nLrozR56qx58jELIjuDNehBm3rcv5U7gtJR_l_gylvrc_JH6-M5kaUytR_VU69LAzOdR9-iEPsCVRRRFeQCGrT3rcvTi8lVl6eWWBsh_ZwVinrdspepMEVx5qSh7VVGRkMHuH55nSVjTvfIcZSChYJhUJJ00NdDxNVq0m00)

saatavuus
* suorituspaikka
* slot

asiakas
* geolokaatio
* katuosoite
* sopimukset

oikeus palveluun
* palvelukoodi
* saatavuus

palvelukoodi

toimipaikkakoodi

sopimus
* palvelukoodit
* toimipaikat

suorituspaikka
* geolokaatio
* käyntiosoite
* ovi

työjono

**Comment by ToniIltanen** [comment]
Voiko sulkea, onko tämä jo resolvattu?

**Comment by jokimaki** [comment]
Suljetaan, ei vastaa nykyistä toteutusta.
